### ISSUE TITLE
downloadable files required for ftp site

### ISSUE THREAD

**Issue by ValWood** [pombase/website#355]
CDS_coordinates, by chromosome - ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/CDS_Coordinates/
exon coordinates - ftp://ftp.pombase.org/pombe/Exon_Coordinates/
see https://github.com/pombase/website/issues/565

 genome 
fasta by chromosome
fasta entire genome
see https://github.com/pombase/website/issues/566

- [ ]  gff    (We need to list the features required in the gff file)
needs to include
see https://github.com/pombase/website/issues/567

- [ ]  manually curated LTRs  from https://github.com/pombase/website/issues/61

- [x] chromosome contigs (already available)

nucleotide cDNA fasta
nucleotide CDS fasta
(for some reason these are currently in the genome directory)
fasta for non cds features https://rt.sanger.ac.uk/SelfService/Display.html?id=533148
see https://github.com/pombase/website/issues/566

- [ ]  complex file  described here https://github.com/pombase/website/issues/273

- [x]  GAF (already available)
- [x]  Phaf  (already available)
- [x] modifications (already available)
- [x] orthologs (already available)

- [x] HCPIN datasets (already available)
ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/exports/

mapping files   transferred to 
https://github.com/pombase/website/issues/564
ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Mappings/
sysID2product.tsv
sysID2product.rna.tsv  (current version contins proten coding psudos!)
allNames.tsv
- [x]  PomBase2UniProt.tsv  this is a static file, replace by https://github.com/pombase/website/issues/562
other files with static content

**Comment by ValWood** [comment]
can be done later

protien data
 - [ ]  peptide stats (non urgent)
- [ ]  protein features (non urgent)
- [ ]   aa composition (non urgent)

UTR 
- [ ]  5'  (non urgent)
- [ ]  3'  (non urgent)

**Comment by ValWood** [comment]
ftp://ftp.ebi.ac.uk/pub/databases/pombase/FASTA/
i don't know why this stuff is separate, need to decide what we need from here
some seems redundant

**Comment by ValWood** [comment]
I think this is actually quite a complete list. I though I opened a ticket recently  (yesterday) to compile this, but I can't find such a ticket

**Comment by mah11** [comment]
We have a FAQ that promises a future downloadable

 - [ ] list of protein-coding genes

(product type = protein and NOT (Characterisation status = dubious OR Characterisation status = transposon))

**Comment by kimrutherford** [comment]
> fasta by chromosome

I can't find that on PomBase V1.  Could you send me the link.

**Comment by kimrutherford** [comment]
It's probably a good time to reorganise.  It's hard to find things.  I think we should get rid of the pombe and DATASET sub-directories and move the contents.  There are some things to remove as well like "EBeyeXML":
  ftp://ftp.pombase.org/

**Comment by ValWood** [comment]
>fasta by chromosome

ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Chromosome_Dumps/fasta/

from
http://www.pombase.org/downloads/genome-datasets
but currently empty?

>It's probably a good time to reorganise. It's hard to find things.

YES PLEASE!

**Comment by ValWood** [comment]
the public stuff has always been under
ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/

I ddn't discover 
ftp://ftp.ebi.ac.uk/pub/databases/pombase/
until recently and we have always made sure that the stuff linked from downloads downloads is under
pombase/pombe/

So we only need to pick the stuff we need from 
pombase/ all other directories

The stuff hosted in the genome browser is here....that's "DATASETS"

The only other useful thing is 
ftp://ftp.ebi.ac.uk/pub/databases/pombase/binding_motifs.bed
which should be in DATASETS

I did once look in the DATASETS directory and notice that it was a bit random....
We can try to rationalise this after public release when you work on JBrowse...
It would be great if we could reach a situation where we can get people to upload their browser trak data in the desired format, and the correct labels, and we don't need to do much but police that it is done correctly....

**Comment by kimrutherford** [comment]
I suggest we move everything on the new FTP site into an "OLD" directory then move things out as we decide where to put them. We can do that live on a Skype call if you like.  I can move and rename things as we decide.

There are a few directories that I think we should rename.  "DATASETS" is one of them. I think it would be clearer to call it something like "external_datasets" or "community_datasets" to make it clear that they aren't things that we have generated.

**Comment by ValWood** [comment]
Yes it would be pretty easy by Skype. Lets do it on this weeks call.

**Comment by kimrutherford** [comment]
> nucleotide cDNA fasta

The current site has three files:

    cdna_introns_utrs.fa.gz
    cdna_nointrons_noutrs.fa.gz
    cdna_nointrons_utrs.fa.gz

Are all three needed?

ftp://ftp.pombase.org/FASTA/

**Comment by ValWood** [comment]
Hmm, not sure. We would have created these because they were asked for, and I could see all 3 being used....

Although the UTR ones are a bit arbitrary because  you would never know if a gene had them (and they are often incorrect).

I would have thought that 
cdna_introns_noutrs.fa.gz was a more common  choice but we don't provide that.

Thoughts anyone?

**Comment by kimrutherford** [comment]
They're easy enough to generate if they're needed.

Perhaps we can improve the file names though.  This one for example gives me a headache:

    cdna_nointrons_noutrs.fa.gz

We shouldn't need to say "nointrons" because a cDNA file shouldn't have introns in it.  And if it hasn't got UTRs it's not cDNA.

I would call that `cds.fa` or `coding_sequences.fa`

**Comment by ValWood** [comment]
yes  you are correct.

Lets go through all the ftp files on the call. I reckon we can do that in an hour....

**Comment by mah11** [comment]
More things I've just noticed now: the documents linked on the legacy-pombase Documents page (http://www.pombase.org/downloads/documents) are a mix of things in the FTP "Archived directories" department and files uploaded in that sodding Drupal system. Can they all have homes somewhere in shiny-new-pombase FTP?

Let me know if you want me to make a list, or if there's any other way I can help.

**Comment by kimrutherford** [comment]
I've been chipping away at generating these files from Chado each night.  There are just three files so far, but I'll add more:
  https://curation.pombase.org/dumps/latest_build/fasta/

**Comment by ValWood** [comment]
This will be so good.
imagine all of the constant checking we won't need to do. The files will just BE THERE!

Can we line wrap at the normal number (60?)

v

**Comment by kimrutherford** [comment]
> Can we line wrap at the normal number (60?)

Yep, will do.

**Comment by kimrutherford** [comment]
>  sysID2product.rna.tsv (current version contins proten coding psudos!)

Just to check, should that contain every type of RNA?

**Comment by ValWood** [comment]
Immediately I didn't think it should contain protein coding pseudo....except that if these do still make mRNA it does  sometimes have a regulatory role....so perhaps the non protein coding pseudo RNAs should be in  here?

**Comment by kimrutherford** [comment]
> non protein coding pseudo RNAs

Do we have any of those?  Could you point me at an example?

**Comment by ValWood** [comment]
Sorry I didn't explain properly.
 ncRNAs by definition are RNAs which do not encode proteins.
If we have an mRNA which no longer encodes a protein, I guess it could be classed as a ncRNA...

We have 28 genes flagged as pseudo. if mist RNAs related to proteins have some regulatory role (and as most of these pseudos have very close paralogs), it is possible, even likely,that the
RNA are regulatory in some capacity.

I'm thinking that the ncRNA file might be the best place for these to be....

**Comment by kimrutherford** [comment]
> Can we line wrap at the normal number (60?)

That's done and will be in tomorrow night's load.

**Comment by kimrutherford** [comment]
Some of the files in your list are now generated nightly.  They appear in this FTP directory:
  ftp://ftp.pombase.org/nightly_update/

These files are now generated nightly:
 - fasta by chromosome
 - fasta entire genome
 - nucleotide CDS fasta
 - also cds+intron sequence, cds+intron+utr sequences, and peptide sequence files in ftp://ftp.pombase.org/nightly_update/fasta/feature_sequences/

These two files:

 - sysID2product.tsv
 - sysID2product.rna.tsv  (not sure I've got this file right)

appear here:  ftp://ftp.pombase.org/nightly_update/misc/

At the moment none of the nightly generated files are copied to ftp://ftp.pombase.org/pombe/ where the rest of the files are.

**Comment by ValWood** [comment]
All in new tickets
